
all: 	execute


execute: shell.c date.c ls.c rm.c mkdir.c cat.c
	
	gcc -o shell shell.c
	gcc -o date date.c
	gcc -o ls ls.c
	gcc -o rm rm.c
	gcc -o mkdir mkdir.c
	gcc -o cat cat.c
	
clean:
	rm shell
	rm date
	rm ls
	rm rm
	rm mkdir
	rm cat

	
